### ISSUE TITLE
Complete documentation and publish fsmglobal repository as pkgdown website

### ISSUE THREAD

**Issue by larnsce** [openwashdata/fsmglobal#1]
```[tasklist]
### Tasks
- [x] Write up README
- [x] Prepare examples in "examples" article
- [x] Collect all authors ORCID iDs
- [x] Confirm variable descriptions
```
